### ISSUE TITLE
all_fields param is not working for the XAS endpoint

### ISSUE THREAD

**Issue by codytodonnell** [materialsproject/api#310]
If using the `all_fields=true` param on the /xas endpoint, the API throws an `Internal Server Error`

e.g. https://api.materialsproject.org/xas/?skip=0&limit=1&all_fields=true

When testing from the docs page, the following error is output in the response:

> Traceback (most recent call last):
  File "/Users/CTODonnell/Documents/venvs/mpapienv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/CTODonnell/Documents/venvs/mpapienv/lib/python3.9/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "/Users/CTODonnell/Documents/venvs/mpapienv/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/CTODonnell/Documents/venvs/mpapienv/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/CTODonnell/Documents/venvs/mpapienv/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/Users/CTODonnell/Documents/venvs/mpapienv/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/Users/CTODonnell/Documents/venvs/mpapienv/lib/python3.9/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/Users/CTODonnell/Documents/venvs/mpapienv/lib/python3.9/site-packages/fastapi/routing.py", line 222, in app
    response_data = await serialize_response(
  File "/Users/CTODonnell/Documents/venvs/mpapienv/lib/python3.9/site-packages/fastapi/routing.py", line 127, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 2 validation errors for Response[XASDoc]
response -> data -> 0 -> symmetry -> crystal_system
  value is not a valid enumeration member; permitted: 'Triclinic', 'Monoclinic', 'Orthorhombic', 'Tetragonal', 'Trigonal', 'Hexagonal', 'Cubic' (type=type_error.enum; enum_values=[<CrystalSystem.tri: 'Triclinic'>, <CrystalSystem.mono: 'Monoclinic'>, <CrystalSystem.ortho: 'Orthorhombic'>, <CrystalSystem.tet: 'Tetragonal'>, <CrystalSystem.trig: 'Trigonal'>, <CrystalSystem.hex_: 'Hexagonal'>, <CrystalSystem.cubic: 'Cubic'>])
response -> errors
  must provide data or error (type=value_error)

**Comment by munrojm** [comment]
This should have been fixed with data patching. I will double check.
