### ISSUE TITLE
Can't get more than 1 structure from setting material_ids in search

### ISSUE THREAD

**Issue by jx-fan** [materialsproject/api#578]
Hi there,

I have a problem with requesting multiple materials with their mp-ids.

The test code is shown below:
```
import mp_api
print(mp_api.__version__)
with mp_api.MPRester() as mpr:
    docs = mpr.thermo.search(material_ids = ["mp-1","mp-10","mp-100"])

print("Number of materials: ", len(docs))
```
The output shows the length of the docs is only 1 although with 3 mp-ids as input:
```
python3 test_new_api.py
0.21.6
/home/jiaxin/miniconda3/lib/python3.8/site-packages/mp_api/client.py:131: builtins.UserWarning: Problem loading MPContribs client: Duplicate operationId: download_entries
Retrieving ThermoDoc documents: 100%|██████████████████████████████████████████████████| 1/1 [00:00<00:00, 27962.03it/s]
Number of materials:  1
```
Can you please help me find out the reason? Or is there another function to query the same information in the new api? 

Thanks for your consideration.
Jiaxin

**Comment by munrojm** [comment]
Hi @jx-fan, try using the `search_thermo_docs` method instead of just `search`.

**Comment by jx-fan** [comment]
Thanks for the quick feedback! It is working now with the `search_thermo_docs` in 0.21.6.

However, when I tested the same code with the freshly out 0.22.0 (really appreciate your hard work!), it shows a REST query error with code 400:

```
python3 test_new_api.py
0.22.0
/home/jiaxin/miniconda3/envs/new_api_env/lib/python3.9/site-packages/mp_api/client.py:140: builtins.UserWarning: Problem loading MPContribs client: Duplicate operationId: download_entries
Traceback (most recent call last):
  File "/home/jiaxin/test_new_api.py", line 4, in <module>
    docs = mpr.thermo.search_thermo_docs(material_ids = ["mp-1","mp-10","mp-100"])
  File "/home/jiaxin/miniconda3/envs/new_api_env/lib/python3.9/site-packages/mp_api/routes/thermo.py", line 112, in search_thermo_docs
    return super().search(
  File "/home/jiaxin/miniconda3/envs/new_api_env/lib/python3.9/site-packages/mp_api/core/client.py", line 812, in search
    return self._get_all_documents(
  File "/home/jiaxin/miniconda3/envs/new_api_env/lib/python3.9/site-packages/mp_api/core/client.py", line 861, in _get_all_documents
    results = self._query_resource(
  File "/home/jiaxin/miniconda3/envs/new_api_env/lib/python3.9/site-packages/mp_api/core/client.py", line 292, in _query_resource
    data = self._submit_requests(
  File "/home/jiaxin/miniconda3/envs/new_api_env/lib/python3.9/site-packages/mp_api/core/client.py", line 399, in _submit_requests
    initial_data_tuples = self._multi_thread(
  File "/home/jiaxin/miniconda3/envs/new_api_env/lib/python3.9/site-packages/mp_api/core/client.py", line 612, in _multi_thread
    data, subtotal = future.result()
  File "/home/jiaxin/miniconda3/envs/new_api_env/lib/python3.9/concurrent/futures/_base.py", line 433, in result
    return self.__get_result()
  File "/home/jiaxin/miniconda3/envs/new_api_env/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/jiaxin/miniconda3/envs/new_api_env/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jiaxin/miniconda3/envs/new_api_env/lib/python3.9/site-packages/mp_api/core/client.py", line 680, in _submit_request_and_process
    raise MPRestError(
mp_api.core.client.MPRestError: REST query returned with error status code 400 on URL https://api.materialsproject.org/thermo/?_all_fields=True&material_ids=mp-1&_limit=334 with message:
Request contains query parameters which cannot be used: _all_fields, _limit
```

Any thoughts on why this happens in the new version? Cheers, Jiaxin

**Comment by munrojm** [comment]
This is a bit of bad timing 😅. The client was just updated to incorporate changes that will be deployed to the API this afternoon. To fix this (for this afternoon only), simply install the previous released version.

**Comment by jx-fan** [comment]
> This is a bit of bad timing 😅. The client was just updated to incorporate changes that will be deployed to the API this afternoon. To fix this (for this afternoon only), simply install the previous released version.

I see:joy:. I guess I was just getting too hyped with the new release but got burnt by the still-hot pie then... thanks for your explanation and remember to always blow on the pie!
