### ISSUE TITLE
allowDiskUse: true

### ISSUE THREAD

**Issue by tschaume** [materialsproject/api#590]
```
pymongo.errors.OperationFailure: Executor error during find command :: caused by :: Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting. Aborting operation. Pass allowDiskUse:true to opt in., full error: {'operationTime': Timestamp(1651016214, 1), 'ok': 0.0, 'errmsg': 'Executor error during find command :: caused by :: Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting. Aborting operation. Pass allowDiskUse:true to opt in.', 'code': 292, 'codeName': 'QueryExceededMemoryLimitNoDiskUseAllowed', '$clusterTime': {'clusterTime': Timestamp(1651016214, 1), 'signature': {'hash': b'-\x1f\x01\xcaZ\xef\xe7\x00\x00\x909dM(\x08\xeb\x86G\xf6T', 'keyId': 7039039845787762689}}}
Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/ddtrace/contrib/asgi/middleware.py", line 173, in __call__
    return await self.app(scope, receive, wrapped_send)
  File "/root/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/root/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/root/.local/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/root/.local/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/root/.local/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/root/.local/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/root/.local/lib/python3.9/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/root/.local/lib/python3.9/site-packages/maggma/api/resource/read_resource.py", line 199, in search
    data = list(self.store.query(**query))
  File "/root/.local/lib/python3.9/site-packages/maggma/stores/mongolike.py", line 403, in query
    for d in self._collection.find(
  File "/root/.local/lib/python3.9/site-packages/pymongo/cursor.py", line 1248, in next
    if len(self.__data) or self._refresh():
  File "/root/.local/lib/python3.9/site-packages/pymongo/cursor.py", line 1165, in _refresh
    self.__send_message(q)
  File "/root/.local/lib/python3.9/site-packages/pymongo/cursor.py", line 1052, in __send_message
    response = client._run_operation(
  File "/root/.local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1267, in _run_operation
    return self._retryable_read(
  File "/root/.local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1371, in _retryable_read
    return func(session, server, sock_info, read_pref)
  File "/root/.local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1263, in _cmd
    return server.run_operation(
  File "/root/.local/lib/python3.9/site-packages/ddtrace/contrib/pymongo/client.py", line 125, in run_operation
    result = self.__wrapped__.run_operation(sock_info, operation, *args, **kwargs)
  File "/root/.local/lib/python3.9/site-packages/pymongo/server.py", line 134, in run_operation
    _check_command_response(first, sock_info.max_wire_version)
  File "/root/.local/lib/python3.9/site-packages/pymongo/helpers.py", line 180, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: Executor error during find command :: caused by :: Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting. Aborting operation. Pass allowDiskUse:true to opt in., full error: {'operationTime': Timestamp(1651016214, 1), 'ok': 0.0, 'errmsg': 'Executor error during find command :: caused by :: Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting. Aborting operation. Pass allowDiskUse:true to opt in.', 'code': 292, 'codeName': 'QueryExceededMemoryLimitNoDiskUseAllowed', '$clusterTime': {'clusterTime': Timestamp(1651016214, 1), 'signature': {'hash': b'-\x1f\x01\xcaZ\xef\xe7\x00\x00\x909dM(\x08\xeb\x86G\xf6T', 'keyId': 7039039845787762689}}}
```

**Comment by tschaume** [comment]
@munrojm I think we still might be getting this error. Would it make sense to add the `allowDiskUse` flag?

**Comment by munrojm** [comment]
Yes it would. I'll add it in `emmet-api`.
