### ISSUE TITLE
DOIRester `search` method (via `mpr.doi.search`) not returns "Not Found"

### ISSUE THREAD

**Issue by sgbaird** [materialsproject/api#612]
```python
doi_fields = ["doi", "bibtex", "task_id"]
nsites = (1, 52)
elements = ["V"]
with MPRester(api_key) as mpr:
    doi_results = mpr.doi.search(nsites=nsites, elements=elements, fields=doi_fields)
```
```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\sterg\Miniconda3\envs\mp-time-split\lib\site-packages\mp_api\core\client.py", line 786, in search
    return self._get_all_documents(
  File "C:\Users\sterg\Miniconda3\envs\mp-time-split\lib\site-packages\mp_api\core\client.py", line 835, in _get_all_documents
    results = self._query_resource(
  File "C:\Users\sterg\Miniconda3\envs\mp-time-split\lib\site-packages\mp_api\core\client.py", line 288, in _query_resource
    data = self._submit_requests(
  File "C:\Users\sterg\Miniconda3\envs\mp-time-split\lib\site-packages\mp_api\core\client.py", line 387, in _submit_requests
    initial_data_tuples = self._multi_thread(use_document_model, initial_params_list)
  File "C:\Users\sterg\Miniconda3\envs\mp-time-split\lib\site-packages\mp_api\core\client.py", line 587, in _multi_thread
    data, subtotal = future.result()
  File "C:\Users\sterg\Miniconda3\envs\mp-time-split\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\sterg\Miniconda3\envs\mp-time-split\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\sterg\Miniconda3\envs\mp-time-split\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\sterg\Miniconda3\envs\mp-time-split\lib\site-packages\mp_api\core\client.py", line 652, in _submit_request_and_process
    raise MPRestError(
mp_api.core.client.MPRestError: REST query returned with error status code 404 on URL https://api.materialsproject.org/doi/?nsites=1&nsites=52&elements=V&_limit=1000&_fields=doi%2Cbibtex%2Ctask_id with message:
Not Found
```

`mpr.doi.get_data_by_id()` seems to work fine:
```python
mpr.doi.get_data_by_id('mp-771054')
```
```bash
DOIDoc(doi='10.17188/1300260', bibtex='@misc{osti_1300260,\n    author = "Persson, Kristin",\n    title = "Materials Data on V3(PO4)2 (SG:2) by Materials Project",\n    abstractNote = "Computed materials data using density functional theory calculations. These calculations determine the electronic structure of bulk materials by solving approximations to the Schrodinger equation. For more information, see https://materialsproject.org/docs/calculations",\n    doi = "10.17188/1300260",\n    place = "United States",\n    year = "2016",\n    month = "2",\n    note = "An optional note"\n}\n', task_id='mp-771054')
```

**Comment by sgbaird** [comment]
Related: https://matsci.org/t/how-do-i-do-a-time-split-of-materials-project-entries-e-g-pre-2018-vs-post-2018/42584/2

**Comment by munrojm** [comment]
Hi @sgbaird, unfortunately the DOI endpoint only has the ability to search with a single MPID at this moment. If getting batches of this data is important to you, let me know and I can help you out.

**Comment by sgbaird** [comment]
@munrojm, thank you - for now I think I have it resolved by pulling all `ProvenanceDoc`-s and cross-referencing against a list of `material_id`-s. https://github.com/materialsproject/api/issues/613#issuecomment-1146391599
