### ISSUE TITLE
Partway through retrieving `SummaryDoc`-s, `MPRestError`: "Response An invalid response was received from the upstream server"

### ISSUE THREAD

**Issue by sgbaird** [materialsproject/api#616]
Started cropping up "randomly". Not sure if something changed upstream, but I was under the impression I'm running the same code I was before with the same `mp_api` version.
```python
(mp-time-split) PS C:\Users\sterg\Documents\GitHub\sparks-baird\mp-time-split> python
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import mp_api
>>> mp_api.__version__
'0.24.0'
```

```python
from mp_api import MPRester
with MPRester(api_key) as mpr:
    results = mpr.summary.search(
        num_sites=(1, 52),
        fields=[
            "structure",
            "material_id",
            "theoretical",
            "energy_above_hull",
            "formation_energy_per_atom",
        ],
    )

```

> ```python
> Retrieving SummaryDoc documents:  21%|▏| 26000/124838 [01Backend TkAgg is interactive backend. Turning interactive mode on.
> Traceback (most recent call last):
>   File "C:\Users\sterg\Miniconda3\envs\mp-time-split\lib\runpy.py", line 197, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Users\sterg\Miniconda3\envs\mp-time-split\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "c:\Users\sterg\.vscode\extensions\ms-python.python-2022.6.3\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
>     cli.main()
>   File "c:\Users\sterg\.vscode\extensions\ms-python.python-2022.6.3\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
>     run()
>   File "c:\Users\sterg\.vscode\extensions\ms-python.python-2022.6.3\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
>     runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
>   File "C:\Users\sterg\Miniconda3\envs\mp-time-split\lib\runpy.py", line 268, in run_path
>     return _run_module_code(code, init_globals, run_name, 
>   File "C:\Users\sterg\Miniconda3\envs\mp-time-split\lib\runpy.py", line 97, in _run_module_code
>     _run_code(code, mod_globals, init_globals,
>   File "C:\Users\sterg\Miniconda3\envs\mp-time-split\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "c:\Users\sterg\Documents\GitHub\sparks-baird\mp-time-split\scripts\data_snapshot.py", line 23, in <module>  
>     expt_df = mpt.fetch_data()
>   File "c:\users\sterg\documents\github\sparks-baird\mp-time-split\src\mp_time_split\core.py", line 94, in fetch_data
>     self.data = fetch_data(
>   File "c:\users\sterg\documents\github\sparks-baird\mp-time-split\src\mp_time_split\utils\data.py", line 121, in fetch_data
>     results = mpr.summary.search(
>   File "C:\Users\sterg\Miniconda3\envs\mp-time-split\lib\site-packages\mp_api\routes\summary.py", line 287, in search
>     return super()._search(
>   File "C:\Users\sterg\Miniconda3\envs\mp-time-split\lib\site-packages\mp_api\core\client.py", line 838, in _search 
>     return self._get_all_documents(
>   File "C:\Users\sterg\Miniconda3\envs\mp-time-split\lib\site-packages\mp_api\core\client.py", line 887, in _get_all_documents
>     results = self._query_resource(
>   File "C:\Users\sterg\Miniconda3\envs\mp-time-split\lib\site-packages\mp_api\core\client.py", line 288, in _query_resource
>     data = self._submit_requests(
>   File "C:\Users\sterg\Miniconda3\envs\mp-time-split\lib\site-packages\mp_api\core\client.py", line 529, in _submit_requests
>     data_tuples = self._multi_thread(use_document_model, params_list, pbar)
>   File "C:\Users\sterg\Miniconda3\envs\mp-time-split\lib\site-packages\mp_api\core\client.py", line 592, in _multi_thread
>     data, subtotal = future.result()
>   File "C:\Users\sterg\Miniconda3\envs\mp-time-split\lib\concurrent\futures\_base.py", line 439, in result
>     return self.__get_result()
>   File "C:\Users\sterg\Miniconda3\envs\mp-time-split\lib\concurrent\futures\_base.py", line 391, in __get_result    
>     raise self._exception
>   File "C:\Users\sterg\Miniconda3\envs\mp-time-split\lib\concurrent\futures\thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "C:\Users\sterg\Miniconda3\envs\mp-time-split\lib\site-packages\mp_api\core\client.py", line 665, in _submit_request_and_process
>     raise MPRestError(
> mp_api.core.client.MPRestError: REST query returned with error status code 502 on URL https://api.materialsproject.org/summary/?nsites_min=1&nsites_max=52&_limit=1000&_fields=structure%2Cmaterial_id%2Ctheoretical%2Cenergy_above_hull%2Cformation_energy_per_atom&_skip=25000 with message:    
> Response An invalid response was received from the upstream server
> ```

**Comment by sgbaird** [comment]
I switched to a different API key and it seems to run OK now. Maybe I was running into issues downloading all `ProvenanceDoc`-s again and again while developing #613
