### ISSUE TITLE
PkgResourcesDeprecationWarning: -PKG-VERSION is an invalid version and will not be supported in a future release

### ISSUE THREAD

**Issue by maungthway** [materialsproject/api#692]
I tried to import MPRester using this commend and get the following warning. Is there a way to fix this warning? 

Code: 
from mp_api.client import MPRester

Warning:
C:\ProgramData\Anaconda3\envs\mp_newapi\lib\site-packages\pkg_resources\__init__.py:123: PkgResourcesDeprecationWarning: -PKG-VERSION is an invalid version and will not be supported in a future release
  warnings.warn(

**Comment by lrodrz** [comment]
On top of this issue, somehow on the fresh pip install I'm getting the following from that same command. 

when using  `from mp_api.client import MPRester`

or even simply using 

`import mp_api.client`


`Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?54c11ac2-932d-47c1-b39f-56532160b56a)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In [13], line 1
----> 1 import mp_api.client

File ~/miniconda3/envs/c-sand/lib/python3.10/site-packages/mp_api/client/__init__.py:4
      2 import os
      3 from pkg_resources import get_distribution, DistributionNotFound
----> 4 from .mprester import MPRester
      5 from .core import MPRestError
      7 try:  # pragma: no cover

File ~/miniconda3/envs/c-sand/lib/python3.10/site-packages/mp_api/client/mprester.py:8
      5 from typing import Dict, List, Optional, Union
      7 from emmet.core.charge_density import ChgcarDataDoc
----> 8 from emmet.core.electronic_structure import BSPathType
      9 from emmet.core.mpid import MPID
     10 from emmet.core.settings import EmmetSettings

File ~/miniconda3/envs/c-sand/lib/python3.10/site-packages/emmet/core/electronic_structure.py:11
      9 import numpy as np
     10 from pydantic import BaseModel, Field
---> 11 from pymatgen.analysis.magnetism.analyzer import (
     12     CollinearMagneticStructureAnalyzer,
     13     Ordering,
...
     62     return settings
     65 SETTINGS = _load_pmg_settings()
---> 66 locals().update(SETTINGS)

ValueError: dictionary update sequence element #0 has length 1; 2 is required`


Suddenly today it stopped working because of this so I tried a fresh `python -m venv env`  installed `mp-api` used the import lines and am getting this error.

**Comment by pmrv** [comment]
This causes a hard crash now for us in [pyiron](https://github.com/pyiron/pyiron_atomistics).  Please advice on a possible fix, I guess in the short term we can downgrade `setuptools`.

We are using versions `pymatgen==2022.11.7`, `mp-api==0.30.5` and `setuptools==66.0.0`.  

Full backtrace
```
   File "/u/zora/software/pyiron_atomistics/pyiron_atomistics/atomistics/structure/factories/materialsproject.py", line 2, in <module>
     from mp_api.client import MPRester
   File "/u/zora/.local/lib/python3.8/site-packages/mp_api/client/__init__.py", line 13, in <module>
     __version__ = get_distribution(__package__).version
   File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 514, in get_distribution
     dist = get_provider(dist)
   File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 386, in get_provider
     return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
   File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 956, in require
     needed = self.resolve(parse_requirements(requirements))
   File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 815, in resolve
     dist = self._resolve_dist(
   File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 844, in _resolve_dist
     env = Environment(self.entries)
   File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1044, in __init__
     self.scan(search_path)
   File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in scan
     self.add(dist)
   File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1096, in add
     dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
   File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2631, in hashcmp
     self.parsed_version,
   File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2678, in parsed_version
     self._parsed_version = parse_version(self.version)
   File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 266, in __init__
     raise InvalidVersion(f"Invalid version: '{version}'")
 pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: 'NOT-A-GIT-REPOSITORY'
```

**Comment by tschaume** [comment]
I can't find a downgrade of `setuptools` in `pyiron` anymore so this seems to be resolved now.
