### ISSUE TITLE
how to solve the bug

### ISSUE THREAD

**Issue by xiaowangfeng** [materialsproject/api#888]
when i run
import pymatgen
from mp_api.client import MPRester
from pymatgen.io.cif import CifWriter

API_KEY = "7d6WsVYuQtxv7IesVAoomDucCAJq5glJ"  # 注册账号时给的KEY，具体位置是官网右上角my DashBoard
mpr = MPRester(API_KEY)  # 创建MPRester对象进行认证

docs = mpr.summary.search(band_gap=value, total_magnetization=value)  # 这里设定搜索条件
id_list = []
for doc in docs:  # 获取材料索引号
    id_list.append(doc.material_id)

for id in id_list:  # 读取材料的晶体结构并且下载
    structure = mpr.get_structure_by_material_id(id)
    cif_writer = CifWriter(structure)
    cif_writer.write_file("SemiDatasets/" + id + ".cif")

Traceback (most recent call last):
  File "E:\materials_discovery-main\materials_discovery-main\untitled\material.py", line 2, in <module>
    from mp_api.client import MPRester
  File "D:\Anaconda\envs\DL\lib\site-packages\mp_api\client\__init__.py", line 8, in <module>
    from .mprester import MPRester
  File "D:\Anaconda\envs\DL\lib\site-packages\mp_api\client\mprester.py", line 10, in <module>
    from emmet.core.electronic_structure import BSPathType
  File "D:\Anaconda\envs\DL\lib\site-packages\emmet\core\electronic_structure.py", line 11, in <module>
    from pymatgen.analysis.magnetism.analyzer import (
  File "D:\Anaconda\envs\DL\lib\site-packages\pymatgen\analysis\magnetism\__init__.py", line 5, in <module>
    from pymatgen.analysis.magnetism.analyzer import (
  File "D:\Anaconda\envs\DL\lib\site-packages\pymatgen\analysis\magnetism\analyzer.py", line 24, in <module>
    from pymatgen.transformations.advanced_transformations import MagOrderingTransformation, MagOrderParameterConstraint
  File "D:\Anaconda\envs\DL\lib\site-packages\pymatgen\transformations\advanced_transformations.py", line 33, in <module>
    from pymatgen.io.ase import AseAtomsAdaptor
  File "D:\Anaconda\envs\DL\lib\site-packages\pymatgen\io\ase.py", line 44, in <module>
    class MSONAtoms(Atoms, MSONable):
NameError: name 'Atoms' is not defined

how  to  solve the bug  i don‘t know     my e-mail：578855392@qq.com

**Comment by xiaowangfeng** [comment]
from mp_api.client import MPRester   it isn't ok。

**Comment by xiaowangfeng** [comment]
which version of Pymatgen can be used?

**Comment by munrojm** [comment]
Reinstall the latest version of the api client and it will enforce the correct pymatgen version.

**Comment by xiaowangfeng** [comment]
thanks，i solve the bug.  i want to download the dataset, but i dont't know how to do it . could you help me? thanks again

**Comment by munrojm** [comment]
You will have to be more specific with what you need

**Comment by xiaowangfeng** [comment]
> You will have to be more specific with what you need

for example      if t nend  to  'Find Si and O containing materials with a band gap greater than 0.5eV but less than 1.0eV', how to find and download the dataset.   thanks
