### ISSUE TITLE
[Bug]: Import Error: MPRester

### ISSUE THREAD

**Issue by minhsueh** [materialsproject/api#939]
### Code snippet

```python
from mp_api.client import MPRester
```

### What happened?

MPRester cannot be imported from the latest mp_api (v0.42.2). It appears to be a dependency issue.

System details:
- Python version: 3.9.12
- Operating System: macOS on an M1 chip

### Version

mp-api v0.42.2

### Which OS?

- [X] MacOS
- [ ] Windows
- [ ] Linux

### Log output

```shell
Traceback (most recent call last):
  File "/Users/chiupeter/Documents/material_informatics/MPShips/mpships/src/mpships/mp_data_stats/mp_status_collecter.py", line 3, in <module>
    from mp_api.client import MPRester
  File "/Users/chiupeter/Documents/material_informatics/MPShips/mpships/.env/lib/python3.9/site-packages/mp_api/client/__init__.py", line 8, in <module>
    from .mprester import MPRester
  File "/Users/chiupeter/Documents/material_informatics/MPShips/mpships/.env/lib/python3.9/site-packages/mp_api/client/mprester.py", line 11, in <module>
    from emmet.core.electronic_structure import BSPathType
  File "/Users/chiupeter/Documents/material_informatics/MPShips/mpships/.env/lib/python3.9/site-packages/emmet/core/electronic_structure.py", line 26, in <module>
    from emmet.core.material_property import PropertyDoc
  File "/Users/chiupeter/Documents/material_informatics/MPShips/mpships/.env/lib/python3.9/site-packages/emmet/core/material_property.py", line 10, in <module>
    from emmet.core.material import PropertyOrigin
  File "/Users/chiupeter/Documents/material_informatics/MPShips/mpships/.env/lib/python3.9/site-packages/emmet/core/material.py", line 13, in <module>
    from emmet.core.structure import MoleculeMetadata, StructureMetadata
  File "/Users/chiupeter/Documents/material_informatics/MPShips/mpships/.env/lib/python3.9/site-packages/emmet/core/structure.py", line 13, in <module>
    from emmet.core.symmetry import PointGroupData, SymmetryData
  File "/Users/chiupeter/Documents/material_informatics/MPShips/mpships/.env/lib/python3.9/site-packages/emmet/core/symmetry.py", line 6, in <module>
    from pymatgen.symmetry.analyzer import (
ImportError: cannot import name 'SymmetryUndeterminedError' from 'pymatgen.symmetry.analyzer' (/Users/chiupeter/Documents/material_informatics/MPShips/mpships/.env/lib/python3.9/site-packages/pymatgen/symmetry/analyzer.py)
```

**Comment by tschaume** [comment]
See this forum thread: https://matsci.org/t/from-mp-api-client-import-mprester-gives-error/58600

**Comment by minhsueh** [comment]
Thank you! @tschaume
